### ISSUE TITLE
segfault when calling  SETFLUIDSdll / SETUPdll

### ISSUE THREAD

**Issue by ericlamnguyen** [usnistgov/REFPROP-cpp-wrapper#2]
Hi Ian,

I encountered a segfault error when running the example test in this repo. Below is what I did:

I'm running a Ubuntu 22.04 distro on WSL2 on a Windows 11 64 bit host machine.

1. I built librefprop.so using the REFPROP-cmake repo and the FORTRAN source files from REFPROP 10.0 installation

2. Clone the REFPROP-cpp-wrapper repo, cd into example/build and run cmake .. && cmake --build . -j4

3. Export RPprefix to the directory where I have the librefprop.so, the .FLD and HMX.BNC files

4. cd into example/build/bin and run the test ./myproject, I got segmentation fault during TestSetFluidsLib (which is the 2nd test in main, the 1st test passed without issue). I ran the test again in debug config in valgrind to get the screenshot below.

![image](https://github.com/usnistgov/REFPROP-cpp-wrapper/assets/35698328/aa57e0be-4b8a-4ada-a35f-1727e7fa8a93)

**Comment by Yaykhel** [comment]
Did you try to change the directory settings in "CMakePresets.json"? Doing so works for my case.

`
      "environment": {
        "RPprefix": "/mnt/c/Program Files (x86)/REFPROP"
`

**Comment by ericlamnguyen** [comment]
Hi Yaykhel,
Thanks for the suggestion.
For myself, I've already exported the RPprefix environment variable to point to where I have the librefprop.so and the fluid files, which is equivalent to modifying the CMakePresets.json file like you are suggesting.

**Comment by ianhbell** [comment]
@Matthew-Boyd  Can you please investigate?

**Comment by Matthew-Boyd** [comment]
Hi Eric,

Can you please try using the Intel compiler instead of the GFortran one? We suspect there may be an issue in the Fortran code that the newest GFortran version is sensitive to (while the Windows, Mac, and Intel compilers are not).

There's some steps for installing the Intel Fortran compiler:
1. Install it from the `intel-basekit`
2. Install the HPC Toolkit
3. Run the included `setvars.sh` to set the system variables

After the compiler is installed, I recommend copying the `/FORTRAN` folder to `/REFPROP-cmake` instead of trying to pass the path in. The CMake command would then be: `cmake .. -DCMAKE_BUILD_TYPE=Release && cmake --build .`

Let us know if you run into more issues.

**Comment by ericlamnguyen** [comment]
Hi Matthew,

Thank you so much for your reply.

Following your suggestion, I've installed Intel Fortran compiler version 2021.1 on my Ubuntu machine. I then recompiled librefprop.so using the FORTRAN files from the official REFPROP 10 installation.

However, I still encountered a segfault error when calling SETFLUIDSdll on single component METHANE. The screenshot below shows where the segfault occured within the fortran code.

![Screenshot 2024-01-06 002558](https://github.com/usnistgov/REFPROP-cpp-wrapper/assets/35698328/997e28bb-89c8-499f-9678-173834c07558)

I've already verified that librefprop.so was loaded properly, and METHANE.FLD is available at the loaded path.
I've also tried to load an incorrect string for component (ie something like "NOT_A_COMPONENT"), and SETFLUIDSdll ran fine and returned code 101 as expected.

Regards,

**Comment by ericlamnguyen** [comment]
Hi Matthew,

I've also tried using the new Intel fortran compiler ifx version 2024.0 to compile the librefprop.so, still got a segfault but the call stack is a little clearer now.

![Screenshot 2024-01-06 012157](https://github.com/usnistgov/REFPROP-cpp-wrapper/assets/35698328/30785873-cf64-4771-a78e-20620f4e2f9b)

Regards.
Eric Nguyen

**Comment by ericlamnguyen** [comment]
Hi Matthew,

I tried to build librefprop.so with ifx in Release config, and instead of a segfault, when running SETFLUIDSdll() I got an error code of 102 back, referring to REFPROP documentation this code means "Error in file or premature end of file". I wonder if this helps to ring any belt. The fluid file I use is the same as those come with REFPROP 10.0 installation.

Regards,
Eric Nguyen

**Comment by Matthew-Boyd** [comment]
This is helpful, thank you. The error code of 102 seems to point to a failure in the read operation, and thus either a problem with the file, the file handle `nread`, or a memory issue.

I am running Intel Fortran Compiler 2021.10.0 on Ubuntu 22.04.3 via WSL2 on 64-bit Windows 10 and I am unfortunately not getting any errors running for methane either.

Are you running your code multithreaded? Maybe @ianhbell has an idea as I am not familiar with the Fortran code or the shared library tool.

**Comment by ericlamnguyen** [comment]
Hi Matthew,

At the moment I'm only running the code with a single thread.

Is it possible that you can help to share the librefprop.so that you built on your machine so that I can use it to run the test on my Linux environment, just to rule out the possibility that something is off with the Fortran compiler on my machine?

Regards,

**Comment by ianhbell** [comment]
The .so built on one machine will not necessarily work on another. This is why we have manylinux for python wheels, for instance.  Better would be to set up a docker container with the necessary code

**Comment by ericlamnguyen** [comment]
Hi Ian,

I asked for the .so because Matthew's setup was very similar to mine, I have Ubuntu 22.04.3 running on WSL2 on a Windows 10  64-bit host, so I thought it can be a simple plug-and-play.

I cloned the Github REFPROP-test repo and used the docker container to build a librefprop.so using the FORTRAN code from REFPROP 10.0 but it still results in a segfault at the read operation inside CORE_ANC.FOR on line 1067

Regards,

**Comment by ianhbell** [comment]
Can you reproduce the error in the conventional CoolProp/REFPROP-headers code? That would help to identify where the problem is coming from.

**Comment by ericlamnguyen** [comment]
Hi Ian,

I cloned the CoolProp/REFPROP-headers and built the executable build/Main, I modified the Main.cpp to change the REFPROP loading path and library name to librefprop.so. I got a few errors as shown below.

![Screenshot 2024-01-08 133322](https://github.com/usnistgov/REFPROP-cpp-wrapper/assets/35698328/21fcaef1-1b47-45c2-836d-675e8d26594d)

![Screenshot 2024-01-08 133205](https://github.com/usnistgov/REFPROP-cpp-wrapper/assets/35698328/a0991710-1a1f-481e-a2fc-34ec39287ee3)

Here's the content of where I have the REFPROP library and fluid files

![Screenshot 2024-01-08 133007](https://github.com/usnistgov/REFPROP-cpp-wrapper/assets/35698328/5221a1ab-c498-42a7-98cc-93db995d336d)

**Comment by ianhbell** [comment]
Can you paste the rest of your Main.cpp?

**Comment by ericlamnguyen** [comment]
Hi Ian,

The rest of Main.cpp was unchanged from the CoolProp/REFPROP-headers repo

![Screenshot 2024-01-08 141919](https://github.com/usnistgov/REFPROP-cpp-wrapper/assets/35698328/d49ad361-d6d9-416c-8999-e9537cfa7f5b)

**Comment by ianhbell** [comment]
I fixed two small issues with the REFPROP-headers repo... 

But having fixed that, I cannot reproduce the crash on either mac or linux (in a docker container running on window host). Makes me think the compilation of the shared library is the problem.

**Comment by ericlamnguyen** [comment]
Hi Ian and Matthew,

It looks like this issue is isolated to my environment, we can close this issue now.

Thank you so much for taking a look into this.

Regards,

**Comment by ianhbell** [comment]
Dumb question, but... have you rebooted? Some memory corruptions can be reset by a reboot. I remember having this experience when I was going deep down the rabbit hole of writing MEX files in MATLAB. Whenever I had a crash, I had corruptions unless I rebooted my computer

**Comment by ericlamnguyen** [comment]
Hi Ian, thanks for the suggestion. I'm running my Ubuntu 22.04 via WSL2 on a Windows host, and I've rebooted my Windows machine a few times but I still encounter the segfault.

**Comment by ianhbell** [comment]
Wonder if this is a WSL bug. Not unheard of, since I don't have the same in docker.
